<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link rel="stylesheet" href="assets/css/normalize.css" />
    <link href="css/magic-check.css" rel="stylesheet">

    <link rel="stylesheet" href="assets/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="assets/css/style.css" />


    <title>Todo list</title>
</head>

<body>
    <header>
        <h1>
        Todo list
    </h1>
    </header>
    <main>
        <form action="inc/delete.php" method="post">
            <ul>
                <?php foreach ($aTasks as $iIndex => $aCols) { ?>
                    <li>

                        <input class="magic-checkbox" id="1" type="checkbox" name="delete[<?= $iIndex;?>]" />
                        <label for="delete"></label>

                        <?php
                        if($aCols[2]<=date("Y-M-D")){ ?>
                            <span class="title level_<?= $aCols[3]; ?>"><?= $aCols[0]; ?> to late</span>
                        <?php }else { ?>
                            <span class="title level_<?= $aCols[3]; ?>"><?= $aCols[0]; ?> </span>
                        <?php }
                        ?>

                        <p class="hidden">
                            <?= $aCols[1]; ?>
                        </p>

                    </li>
                    <?php } ?>
            </ul>
            <input type="submit" value="Delete" />
        </form>
        <form method="post" action="inc/add.php">
            <fieldset>

                <label for="title"> Title </label>
                <input type="text" name="title" value="" placeholder="Le titre de votre tâche" />
            </fieldset>
            <fieldset>
                <label for="message"> Description </label>
                <textarea name="message" rows="10" cols="30"></textarea>
            </fieldset>
            <fieldset>
                <label for="date"> Date </label>
                <input type="date" name="date" value="" pattern="(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))" />
            </fieldset>
            <fieldset>

                <input id="2" class="magic-radio" type="radio" name="important" value="3" />
                <label for="2">Important</label>

                <input id="2" class="magic-radio" type="radio" name="important" value="2" />
                <label for="2">Normal</label>

                <input id="2" class="magic-radio" type="radio" name="important" value="1" />
                <label for="2">pas important</label>
            </fieldset>
            <fieldset>
                <input type="submit" value="Enter" name="envoi" />
            </fieldset>

        </form>


    </main>
    <footer>

    </footer>
    <!--  <script src="js/general.js" ></script>-->

</body>

</html>