<!DOCTYPE html>
<html>
	<head>
		<title>Mon Blog</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

 		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="assets/css/style.css" />
	</head>
	
	<body>
	<div class="navbar navbar-inverse navbar-static-top">
	  <div class="container">
	    <div class="navbar-collapse collapse">
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="index.php">Accueil</a></li>
	        <li><a href="index.php?page=add_post">Ajouter un post</a></li>
	      </ul>
	    </div>
	  </div>
	</div>