<?php if(isset($error_message)){ ?>
<p><?= htmlspecialchars($error_message); ?></p>
<?php } ?>
<form method="POST" action="">
    <fieldset>
        <label for="FirstName">First name*</label>
    <input type="text" name="FirstName" required value=""/>
        <label for="LastName">Last name*</label>
            <input type="text" name="LastName" required/>

    </fieldset>

    <fieldset>
        <label for="Email">Email*</label>
        <input type="email" name="Email" required/>

        <label for="BirthDate">Birthdate</label>
        <input type="date" name="BirthDate" />

    </fieldset>

    <fieldset>
        <label for="Password">Password*</label>
        <input type="password" name="Password" required/>
        <label for="controllpwd">rewrite Password*</label>
        <input type="password" name="controllpwd" required/>

    </fieldset>


    <fieldset>
        <label for="Address">Address*</label>
        <input type="text" name="Address" required/>
        <label for="City">City*</label>
        <input type="text" name="City" required/>

    </fieldset>

    <fieldset>
        <label for="ZipCode">Zipcode*</label>
        <input type="number"  maxlength="5" name="ZipCode" required/>
        <label for="Country">Country</label>
        <input type="text" name="Country" />

    </fieldset>
    <fieldset>
        <label for="Phone">Phone*</label>
        <input type="tel"  pattern="^((\+\d{1,3}(-| )?\(?\d\)?(-| )?\d{1,5})|(\(?\d{2,6}\)?))(-| )?(\d{3,4})(-| )?(\d{4})(( x| ext)\d{1,5}){0,1}$" name="Phone" required/>


    </fieldset>
    <input type="submit"  value="Inscription"/> <br />
*required

</form>





