<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link rel="stylesheet" href="assetscss/normalize.css" />
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="assets/css/style.css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="assets/js/ajax.js"></script>
    <script src="assets/js/event.js"></script>




    <title>ajax</title>
</head>

<body>
<header>

</header>
<main>
    <section id="target">
        <em>Results</em>
    </section>

    <form>
        <fieldset>
            <legend><i class="fa fa-question-circle"></i> Choisir</legend>
            <ul>
                <li>
                    <input type="radio" name="what" value="1" id="html" checked>
                    <label for="html">get html</label>
                </li>
                <li>
                    <input type="radio" name="what" value="2" id="json">
                    <label for="json">Get json</label>
                </li>
                <li>
                    <input type="radio" name="what" value="3" id="movies">
                    <label for="movies">Les films</label>
                </li>
                <li>
                    <button type="button" id="run">GO</button>
                </li>
            </ul>
        </fieldset>
    </form>



</main>
<footer>

</footer>
<script src="assets/js/main.js"></script>
</body>

</html>