<?php if(isset($error_message)){ ?>
<p><?= $error_message; ?></p>
<?php } ?>
<form method="POST" action="">
    <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <span id="total-error-count">1</span> erreur(s) dans le formulaire !</h3>
        <p></p>
    </aside>

    <fieldset>
        <label for="FirstName">First name*</label>


    <input type="text" name="FirstName" value="<?= (isset($FirstName) ?
          htmlspecialchars($FirstName): ''); ?>" required />
        <label for="LastName">Last name*</label>
            <input type="text" name="LastName"  value="<?= (isset($LastName) ?
                htmlspecialchars($LastName): ''); ?>" required/>

    </fieldset>

    <fieldset>
        <label for="Email">Email*</label>
        <input type="email" name="Email"  value="<?= (isset($Email) ?
            htmlspecialchars($Email): ''); ?>" required/>

        <label for="BirthDate">Birthdate</label>
        <input type="date" name="BirthDate"  value="<<?= (isset($BirthDate) ?
            htmlspecialchars($BirthDate): ''); ?>" />

    </fieldset>

    <fieldset>
        <label for="Password">Password*</label>
        <input type="password" name="Password" data-name="password" data-length="5" value="<?= (isset($Password) ?
            htmlspecialchars($Password): ''); ?>" required/>
        <label for="controllpwd">rewrite Password*</label>
        <input type="password" name="controllpwd" data-length="5" data-name="verifier_password" value="<?= (isset($controllpwd) ?
            htmlspecialchars($controllpwd): ''); ?>" required/>

    </fieldset>


    <fieldset>
        <label for="Address">Address*</label>
        <input type="text" name="Address"  value="<?= (isset($Address) ?
            htmlspecialchars($Address): ''); ?>" required/>
        <label for="City">City*</label>
        <input type="text" name="City" value="<?= (isset($City) ?
            htmlspecialchars($City): ''); ?>" required/>

    </fieldset>

    <fieldset>
        <label for="ZipCode">Zipcode*</label>
        <input type="number"  maxlength="5" name="ZipCode"  value="<?= (isset($ZipCode) ?
            htmlspecialchars($ZipCode): ''); ?>" required/>
        <label for="Country">Country</label>
        <input type="text" name="Country" value="<?= (isset($Country) ?
            htmlspecialchars($Country): ''); ?>"/>

    </fieldset>
    <fieldset>
        <label for="Phone">Phone*</label>
        <input type="tel"  pattern="^((\+\d{1,3}(-| )?\(?\d\)?(-| )?\d{1,5})|(\(?\d{2,6}\)?))(-| )?(\d{3,4})(-| )?(\d{4})(( x| ext)\d{1,5}){0,1}$" name="Phone"  value="<?= (isset($Phone) ?
            htmlspecialchars($Phone): ''); ?>" required/>


    </fieldset>
    <input type="submit"  id="submit" value="Inscription"/> <br />
*required

</form>





