<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link rel="stylesheet" href="assets/css/normalize.css" />
    <link rel="stylesheet" href="assets/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="assets/css/style.css" />


    <title>traductor</title>
</head>

<body>
    <header>
        <h1>Traducteur Anglais - Français</h1>
    </header>

    <main>
        <main>
            <form action="index.php" method="POST">
                <ul>
                    <li>
                        <label for="word">Mot :</label>
                        <input type="text" id="word" name="word">
                    </li>
                    <li>
                        <label for="direction">Sens de traduction :</label>
                        <select id="direction" name="direction">
                            <option value="toEnglish">Français vers Anglais</option>
                            <option value="toFrench">Anglais vers Français</option>
                        </select>
                    </li>
                    <li>
                        <input type="submit" value="Traduire">
                    </li>
                </ul>
            </form>

            <?php if(!empty($sErrorMsg)){?>
                <div class="error">
                    <?=$sErrorMsg?>
                </div>
                <?php }else {?>
                    <div class="error">
                        <?= $sText; ?>
                    </div>
                    <?php } ?>
        </main>


    </main>
    <footer>

    </footer>
    <!--  <script src="js/general.js" ></script>-->
</body>

</html>